spring.datasource.url=jdbc:mysql://localhost:3306/eshop_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=eshop_dev
# spring.datasource.password=eshop_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache=false
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG